name: Publish CMS Updates to App

on:
  push:
    branches:
      - main
    paths:
      - 'kigali-health-info/data/**' 

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kigali-health-info 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x # UPDATED to match your local computer

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm # Forces Expo to use npm instead of yarn

      - name: Install Dependencies
        run: npm install

      - name: Publish EAS Update
        run: eas update --branch production --message "Automated update from Decap CMS" --non-interactive